### ISSUE TITLE
Exception at MedLaunch.Classes.IO.MedDiscUtils.GetPSXSerial(String path)

### ISSUE THREAD

**Issue by vkapartzianis** [Asnivor/MedLaunch#105]
I'm getting an exception while trying to import a specific PSX CD image. The game is "Gunner's Heaven" (SCPS-10006), a complete stack trace is below. Can you check it out please? Note that Mednafen and other emulators (ePSXe, PCSXR) are able to load the image just fine -- there's no sign it's corrupted.

```
******************** Exception detail - 2017-03-20 07:26:21 - ********************

HResult:    -2147467261
HelpLink:   
Message:    Object reference not set to an instance of an object.
Source:     MedLaunch
StackTrace:    at MedLaunch.Classes.IO.MedDiscUtils.GetPSXSerial(String path)
   at MedLaunch.Classes.Scanning.DiscScan.InsertOrUpdateDisk(DiscGameFile f, Int32 sysId)
   at MedLaunch.Classes.Scanning.DiscScan.BeginManualImport(Int32 sysId)
   at MedLaunch.MainWindow.ManualAddGame_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



****************************************

******************** Exception detail - 2017-03-20 07:26:21 - ********************

HResult:    -2147467261
HelpLink:   
Message:    Object reference not set to an instance of an object.
Source:     MedLaunch
StackTrace:    at MedLaunch.Classes.IO.MedDiscUtils.GetPSXSerial(String path)
   at MedLaunch.Classes.Scanning.DiscScan.InsertOrUpdateDisk(DiscGameFile f, Int32 sysId)
   at MedLaunch.Classes.Scanning.DiscScan.BeginManualImport(Int32 sysId)
   at MedLaunch.MainWindow.ManualAddGame_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at MedLaunch.App.Main()
```

**Comment by Asnivor** [comment]
So I was under the (mistaken) impression that all PSX disc images have their game serial number embedded in the image (either in the SYSTEM.CNF file or as a standalone file in the ISO format).

For this game at least I can find no trace of the serial number at all. I've updated the serial number code with better error handling to resolve this issue. This will be in the next release.

Thanks!
