### ISSUE TITLE
Certain games crash Medlaunch if I try to select them after an update

### ISSUE THREAD

**Issue by ghost** [Asnivor/MedLaunch#215]
******************** Exception detail - 21.04.2018 11:01:19 - ********************

HResult:    -2146233066
HelpLink:   
Message:    TimeSpan overflowed because the duration is too long.
Source:     mscorlib
StackTrace:    at System.TimeSpan.Interval(Double value, Int32 scale)
   at System.TimeSpan.FromMinutes(Double value)
   at MedLaunch.Classes.GamesLibraryVisualHandler.FormatMinutesToString(Double minutes)
   at MedLaunch.Classes.GamesLibraryVisualHandler.<>c__DisplayClass3_0.<DoSidebarUpdate>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

****************************************

******************** Exception detail - 21.04.2018 11:01:19 - ********************

HResult:    -2146233066
HelpLink:   
Message:    TimeSpan overflowed because the duration is too long.
Source:     mscorlib
StackTrace:    at System.TimeSpan.Interval(Double value, Int32 scale)
   at System.TimeSpan.FromMinutes(Double value)
   at MedLaunch.Classes.GamesLibraryVisualHandler.FormatMinutesToString(Double minutes)
   at MedLaunch.Classes.GamesLibraryVisualHandler.<>c__DisplayClass3_0.<DoSidebarUpdate>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MedLaunch.App.Main()

****************************************

MedLaunch freezes once I click on them and then crashes shortly after. They all worked fine before I've updated to the latest version. 

I used to have the same problem before with a previous update. The only solution was to delete and re-scrape all of my games.

**Comment by Asnivor** [comment]
This should now be sorted in the latest dev build
