### ISSUE TITLE
Crashes when I scan for discs

### ISSUE THREAD

**Issue by fcocarlos2** [Asnivor/MedLaunch#217]
Every time I try and scan for disks the program crashes. 

****************************************

******************** Exception detail - 01/05/2018 00:30:45 - ********************

HResult:    -2146233080
HelpLink:   
Message:    O índice estava fora dos limites da matriz.
Source:     MedLaunch
StackTrace:    em MedLaunch.Classes.Scanning.DiscScan.DetermineAllGamesInFolder(String folderPath, Int32 sysId)
   em MedLaunch.Classes.Scanning.DiscScan.BeginDiscImportImproved(Int32 systemId, ProgressDialogController dialog)
   em MedLaunch.MainWindow.<>c__DisplayClass100_0.<RescanSystemDiscs>b__1()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em MedLaunch.MainWindow.<RescanSystemDiscs>d__100.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em System.Windows.Application.Run(Window window)
   em System.Windows.Application.Run()
   em MedLaunch.App.Main()

****************************************

**Comment by ghost** [comment]
Yep, same issue


```

******************** Exception detail - 5/2/2018 4:39:24 PM - ********************

HResult:    -2146233080
HelpLink:   
Message:    Index was outside the bounds of the array.
Source:     MedLaunch
StackTrace:    at MedLaunch.Classes.Scanning.DiscScan.DetermineAllGamesInFolder(String folderPath, Int32 sysId)
   at MedLaunch.Classes.Scanning.DiscScan.BeginDiscImportImproved(Int32 systemId, ProgressDialogController dialog)
   at MedLaunch.MainWindow.<>c__DisplayClass100_0.<RescanSystemDiscs>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MedLaunch.MainWindow.<RescanSystemDiscs>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



****************************************

******************** Exception detail - 5/2/2018 4:39:24 PM - ********************

HResult:    -2146233080
HelpLink:   
Message:    Index was outside the bounds of the array.
Source:     MedLaunch
StackTrace:    at MedLaunch.Classes.Scanning.DiscScan.DetermineAllGamesInFolder(String folderPath, Int32 sysId)
   at MedLaunch.Classes.Scanning.DiscScan.BeginDiscImportImproved(Int32 systemId, ProgressDialogController dialog)
   at MedLaunch.MainWindow.<>c__DisplayClass100_0.<RescanSystemDiscs>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MedLaunch.MainWindow.<RescanSystemDiscs>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MedLaunch.App.Main()



****************************************


```

an array out of bounds issue, should be a trivial fix.

**Comment by Asnivor** [comment]
Sorry chaps, I have been really busy recently. I will try and look at this later today.

**Comment by ghost** [comment]
I had a look over MedLaunch.Classes.Scanning.DiscScan.DetermineAllGamesInFolder but the array indexing error didn't immediately jump at me, likely due to my unfamilarity with C# - sorry, I was gonna make a pull request (if only it were ANSI C...) but you'll have to put in the effort for finding it.

**Comment by Asnivor** [comment]
I believe this is related to #213 and is probably to do with non-standard characters somewhere along the way. I will try and give it my attention tonight.

**Comment by fcocarlos2** [comment]
That's okay. I understand it is complicated developing a software alone.

**Comment by fcocarlos2** [comment]
Which non-standard characters are these? I could check this here in my ROMs.

**Comment by Asnivor** [comment]
Potentially the tilde '~' might be causing issues. Also maybe unicode characters (although I am not sure of this yet)

**Comment by fcocarlos2** [comment]
I erased all ' in the games names and it still doesn't run. Should I erase all ( ) [ ] - _ too?

**Comment by fcocarlos2** [comment]
And there was no tilde

**Comment by Asnivor** [comment]
I doubt that will help then. It should be robust enough to handle normal ascii characters. It must be something else, although I havent had a chance to look at it properly.

Hopefully I will have time this weekend. Thanks for your help so far.

**Comment by ghost** [comment]
My tree has no nonstandard characters I can find, for verification:

$> D:
$> cd D:\Emulators\isos and roms\PS1
$> tree /F /A > tree.txt

the paths have no special characters, the file names and subdirectories don't either. (and you should be parsing proper unicode if you aren't, otherwise you get weird bugs)

```

Folder PATH listing
Volume serial number is REDACTED
D:.
|   Final Fantasy VIII - Disc1 [SLUS-00907].ccd
|   Final Fantasy VIII - Disc1 [SLUS-00907].img
|   Final Fantasy VIII - Disc1 [SLUS-00907].sub
|   Final Fantasy VIII - Disc2 [SLUS-00908].ccd
|   Final Fantasy VIII - Disc2 [SLUS-00908].img
|   Final Fantasy VIII - Disc2 [SLUS-00908].sub
|   Final Fantasy VIII - Disc3 [SLUS-00909].ccd
|   Final Fantasy VIII - Disc3 [SLUS-00909].img
|   Final Fantasy VIII - Disc3 [SLUS-00909].sub
|   Final Fantasy VIII - Disc4 [SLUS-00910].ccd
|   Final Fantasy VIII - Disc4 [SLUS-00910].img
|   Final Fantasy VIII - Disc4 [SLUS-00910].sub
|   legends.ccd
|   legends.img
|   legends.sub
|   legends2.ccd
|   legends2.img
|   legends2.sub
|   Megaman X5.bin
|   Megaman X5.cue
|   Nightmare Creatures II [U] [SLUS-01112].ccd
|   Nightmare Creatures II [U] [SLUS-01112].img
|   Nightmare Creatures II [U] [SLUS-01112].sub
|   Spiderman [U] [SLUS-00875].ccd
|   Spiderman [U] [SLUS-00875].img
|   Spiderman [U] [SLUS-00875].sub
|   Spyro the Dragon (US NTSC).bin
|   Spyro the Dragon (US NTSC).cue
|   Yu-Gi-Oh! Forbidden Memories (USA).bin
|   Yu-Gi-Oh! Forbidden Memories (USA).cue
|   
+---Castlevania - Symphony of the Night [U] [SLUS-00067]
|   \---Castlevania Symphany
|           Castlevania.bin
|           Castlevania.cue
|           
+---Code Breaker (USA) (Unl)
|       Code Breaker (USA) (Unl).bin
|       Code Breaker (USA) (Unl).cue
|       
+---Crash Bandicoot 2 - Cortex Strikes Back [U] [SCUS-94154]
|       Crash 2.bin
|       Crash 2.cue
|       
+---Crash Bandicoot 3 - Warped [U] [SCUS-94244]
|       Crash Bandicoot 3.bin
|       Crash Bandicoot 3.cue
|       
+---Crash Bandicoot [U] [SCUS-94900]
|       Crash Bandicoot [U] [SCUS-94900].ccd
|       Crash Bandicoot [U] [SCUS-94900].img
|       Crash Bandicoot [U] [SCUS-94900].sub
|       
+---Croc - Legend of the Gobbos [U] [SLUS-00530]
|       Croc - Legend of the Gobbos [U] [SLUS-00530].ccd
|       Croc - Legend of the Gobbos [U] [SLUS-00530].img
|       Croc - Legend of the Gobbos [U] [SLUS-00530].sub
|       
+---Disney's Hercules [U] [SLUS-00529]
|       Disney's Hercules [U] [SLUS-00529].bin
|       Disney's Hercules [U] [SLUS-00529].cue
|       
+---Driver 2 [Disc1of2] [U] [SLUS-01161]
|       Driver 2 [Disc1of2] [U] [SLUS-01161].ccd
|       Driver 2 [Disc1of2] [U] [SLUS-01161].img
|       Driver 2 [Disc1of2] [U] [SLUS-01161].sub
|       
+---Driver 2 [Disc2of2] [U] [SLUS-01318]
|   \---Driver 2 [Disc2of2] [SLUS-01318] [bin]
|           Driver 2 [Disc2of2] [SLUS-01318].bin
|           Driver 2 [Disc2of2] [SLUS-01318].cue
|           
+---Driver [U] [SLUS-00842]
|   \---Driver [SLUS-00842] [img]
|           Driver [SLUS-00842].ccd
|           Driver [SLUS-00842].cue
|           Driver [SLUS-00842].img
|           Driver [SLUS-00842].sub
|           
+---Fantastic Four [U] [SLUS-00395]
|       Fantastic_Four.ccd
|       Fantastic_Four.cue
|       Fantastic_Four.img
|       Fantastic_Four.sub
|       
+---FM II ultimate
|       FM II ultimate.iso
|       
+---FMR extracted files
|   |   SLUS_014.11
|   |   SYSTEM.CNF
|   |   
|   \---DATA
|           MASTER.XA
|           MODEL.MRG
|           MOVIE.STR
|           mrgSU_xax_mrg_m000.dat
|           SD_BGM.DAT
|           SD_SE.DAT
|           SU.MRG
|           WA_MRG.MRG
|           
+---Gran Turismo [U] [SCUS-94194]
|       Gran Turismo [U] [SCUS-94194].ccd
|       Gran Turismo [U] [SCUS-94194].img
|       Gran Turismo [U] [SCUS-94194].sub
|       
+---Harry Potter & The Sorcerer's Stone [U] [SLUS-01415]
|   \---Harry Potter and The Sorcerer's Stone [SLUS-01415] [bin]
|           Harry Potter and The Sorcerer's Stone [SLUS-01415].bin
|           Harry Potter and The Sorcerer's Stone [SLUS-01415].cue
|           
+---Harry Potter and the Chamber of Secrets [U] [SLUS 01503]
|       Harry Potter and the Chamber of Secrets [SLUS_015.03].mdf
|       Harry Potter and the Chamber of Secrets [SLUS_015.03].mds
|       
+---IMBNES
|       IMBNES.iso
|       
+---iplightus
|       iplight.bin
|       iplight.cue
|       
+---Jersey Devil [U] [SCUS-94907]
|       Jersey Devil.bin
|       Jersey Devil.cue
|       
+---Jojo's Bizarre Adventure [U] [SLUS-01060]
|       Jojo's Bizarre Adventure [U] [SLUS-01060].ccd
|       Jojo's Bizarre Adventure [U] [SLUS-01060].img
|       Jojo's Bizarre Adventure [U] [SLUS-01060].sub
|       
+---Legend of Legaia (ccd)[SCUS-94254]
|       LegendOfLegaia.ccd
|       LegendOfLegaia.img
|       LegendOfLegaia.sub
|       
+---Legend of Mana (ccd)[SLUS-01013]
|       Legend of Mana.ccd
|       Legend of Mana.cue
|       Legend of Mana.img
|       Legend of Mana.sub
|       
+---Megaman Legends 2 [SLUS-01140]
|       legends2.ccd
|       legends2.img
|       legends2.sub
|       
+---Megaman Legends [SLUS-00603]
|       legends.ccd
|       legends.img
|       legends.sub
|       
+---Misadventures of Tron Bonne; The [U] [SLUS-00896]
|       The Misadventures of Tron Bonne.ccd
|       The Misadventures of Tron Bonne.cue
|       The Misadventures of Tron Bonne.img
|       The Misadventures of Tron Bonne.sub
|       
+---Net Yaroze Collection 2014
|       Net Yaroze 2014 (NTSC).ISO
|       Net Yaroze 2014 (PAL & NTSC).ISO
|       Net Yaroze 2014 (PAL).ISO
|       Readme.txt
|       
+---Nightmare Creatures II [U] [SLUS-01112]
|       Nightmare Creatures II [U] [SLUS-01112].ccd
|       Nightmare Creatures II [U] [SLUS-01112].img
|       Nightmare Creatures II [U] [SLUS-01112].sub
|       
+---Nightmare Creatures [U] [SLUS-00582]
|       SLUS_00582.ccd
|       SLUS_00582.img
|       SLUS_00582.sub
|       
+---Road Rash - Jailbreak [U] [SLUS-01053]
|       Road Rash Jailbreak.ccd
|       Road Rash Jailbreak.cue
|       Road Rash Jailbreak.img
|       Road Rash Jailbreak.sub
|       
+---Road Rash 3D [U] [SLUS-00524]
|       Road Rash 3D.ccd
|       Road Rash 3D.cue
|       Road Rash 3D.img
|       Road Rash 3D.sub
|       
+---Road Rash [U] [SLUS-00035]
|       Road Rash [U] [SLUS-00035].bin
|       Road Rash [U] [SLUS-00035].cue
|       
+---Sled Storm [U] [SLUS-00955]
|   \---Sled Storm [SLUS-00955] [img]
|           Sled Storm [SLUS-00955].ccd
|           Sled Storm [SLUS-00955].img
|           Sled Storm [SLUS-00955].sub
|           
+---Space Hulk - Vengeance of the Blood Angels [U] [SLUS-00205]
|       Space Hulk - Vengeance of the Blood Angels.ccd
|       Space Hulk - Vengeance of the Blood Angels.img
|       Space Hulk - Vengeance of the Blood Angels.sub
|       
+---Spiderman 2 - Enter Electro [U] [SLUS-01378]
|       Spiderman II - Enter Electro.ccd
|       Spiderman II - Enter Electro.img
|       Spiderman II - Enter Electro.sub
|       
+---Spiderman [U] [SLUS-00875]
|       Spiderman [U] [SLUS-00875].ccd
|       Spiderman [U] [SLUS-00875].img
|       Spiderman [U] [SLUS-00875].sub
|       
+---Spyro the Dragon 2 - Ripto's Rage [U] [SCUS-94425]
|       Spyro the Dragon 2 - Ripto's Rage [U] [SCUS-94425].ccd
|       Spyro the Dragon 2 - Ripto's Rage [U] [SCUS-94425].img
|       Spyro the Dragon 2 - Ripto's Rage [U] [SCUS-94425].sub
|       
+---Spyro the Dragon 3 - Year of the Dragon [U] [SCUS-94467]
|       NEW.ccd
|       NEW.img
|       NEW.sub
|       
+---Spyro the Dragon [U] [SCUS-94228]
|       Spyro the Dragon (US NTSC).bin
|       Spyro the Dragon (US NTSC).cue
|       
+---Star Wars - Dark Forces [U] [SLUS-00297]
|   |   Star Wars - Dark Forces [SLUS-00297].ccd
|   |   Star Wars - Dark Forces [SLUS-00297].img
|   |   Star Wars - Dark Forces [SLUS-00297].sub
|   |   
|   \---Star Wars - Dark Forces [SLUS-00297]
+---Star Wars - Demolition [U] [SLUS-01183]
|       Star Wars Demolition.bin
|       Star Wars Demolition.cue
|       
+---Star Wars - Episode I - Jedi Power Battle [U] [SLUS-01046]
|   \---Star Wars - Episode I - Jedi Power Battle [SLUS-01046] [U]
|           Star Wars - Episode I - Jedi Power Battle [SLUS-01046] [U].ccd
|           Star Wars - Episode I - Jedi Power Battle [SLUS-01046] [U].img
|           Star Wars - Episode I - Jedi Power Battle [SLUS-01046] [U].sub
|           
+---Star Wars - Episode I - The Phantom Menace [U] [SLUS-00884]
|       Star Wars - Episode I - The Phantom Menace [U] [SLUS-00884].ccd
|       Star Wars - Episode I - The Phantom Menace [U] [SLUS-00884].img
|       Star Wars - Episode I - The Phantom Menace [U] [SLUS-00884].sub
|       
+---Tank_Racer_PAL
|       Tank_Racer_PAL.bin
|       Tank_Racer_PAL.cue
|       Tank_Racer_PAL_Cover.jpg
|       
+---Tekken 2 [U] [SLUS-00213]
|       Tekken 2.bin
|       Tekken 2.cue
|       
+---Tekken 3 [U] [SLUS-00402]
|   \---Tekken 3 PSX
|           Tekken 3.bin
|           Tekken 3.cue
|           
+---Tekken [U] [SLUS-00006]
|       Tekken [U] [SLUS-00006].ccd
|       Tekken [U] [SLUS-00006].img
|       Tekken [U] [SLUS-00006].sub
|       
+---Tony Hawk's Pro Skateboarding [U] [SLUS-00860]
|   \---Tony Hawk's Pro Skater (U) (SLUS_008.60)
|           SLUS_008.60.bin
|           SLUS_008.60.cue
|           
+---Tony Hawk's Pro Skater 2 [U] [SLUS-01066]
|       Tony Hawk's Pro Skater 2 [U] [SLUS-01066].ccd
|       Tony Hawk's Pro Skater 2 [U] [SLUS-01066].img
|       Tony Hawk's Pro Skater 2 [U] [SLUS-01066].sub
|       
+---Tony Hawk's Pro Skater 4 [U] [SLUS-01485]
|       Tony Hawk's Pro Skater 4 [U] [SLUS-01485].BIN
|       Tony Hawk's Pro Skater 4 [U] [SLUS-01485].CUE
|       
+---Tony Hawks Pro Skater 3 [U] [SLUS-01419]
|       Tony Hawk`s Pro Skater 3 [U] [SLUS-01419].ccd
|       Tony Hawk`s Pro Skater 3 [U] [SLUS-01419].img
|       Tony Hawk`s Pro Skater 3 [U] [SLUS-01419].sub
|       
+---Top Gun - Fire at Will [U] [SLUS-00032]
|       TopGunFAW.ccd
|       TopGunFAW.cue
|       TopGunFAW.img
|       TopGunFAW.sub
|       
+---Wipeout 3 [U] [SLUS-00865]
|       Wipeout 3 [U] [SLUS-00865].bin
|       Wipeout 3 [U] [SLUS-00865].cue
|       
+---Wipeout XL [U] [SCUS-94351]
|       Wipeout XL [U] [SCUS-94351].ccd
|       Wipeout XL [U] [SCUS-94351].cue
|       Wipeout XL [U] [SCUS-94351].img
|       Wipeout XL [U] [SCUS-94351].sub
|       
+---Wipeout [U] [SCUS-94301]
|       Wipeout SCUS_943.01.bin
|       Wipeout SCUS_943.01.cue
|       
+---Worms Armageddon [U] [SLUS-00888]
|       Worms Armageddon [U] [SLUS-00888].ccd
|       Worms Armageddon [U] [SLUS-00888].cue
|       Worms Armageddon [U] [SLUS-00888].img
|       Worms Armageddon [U] [SLUS-00888].sub
|       
+---Worms World Party [U] [SLUS-01448]
|       SLUS-01448.bin
|       SLUS-01448.cue
|       
+---Worms [U] [SLUS-00336]
|       Worms [U] [SLUS-00336].ccd
|       Worms [U] [SLUS-00336].img
|       Worms [U] [SLUS-00336].sub
|       
\---Yu-Gi-Oh! Forbidden Memories (USA)
        Yu-Gi-Oh! Forbidden Memories (USA).bin
        Yu-Gi-Oh! Forbidden Memories (USA).cue
        

```

**Comment by fcocarlos2** [comment]
You are welcome, Asnivor. I wish you good luck for this weekend :)
